services:
  # Redis broker for Celery
  - type: redis
    name: learning-platform-redis
    plan: free

  # Django Backend API
  - type: web
    name: learning-platform-api
    env: python
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py flush --no-input
      python seed.py
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 2 --max-requests 1000 --max-requests-jitter 50 learning_platform.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: learning_platform.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "learning-platform-api.onrender.com,learning-platform-web.onrender.com,localhost,127.0.0.1,*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://learning-platform-web.onrender.com"
      - key: FRONTEND_URL
        value: "https://learning-platform-web.onrender.com"
      - key: BACKEND_URL
        value: "https://learning-platform-api-kwp9.onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: BREVO_API_KEY
        value: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: TIME_ZONE
        value: "Asia/Ho_Chi_Minh"
        
      - key: PYTHON_VERSION
        value: "3.11.10"
      # Social login
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        sync: false
      - key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        sync: false
      - key: SOCIAL_AUTH_GITHUB_KEY
        sync: false
      - key: SOCIAL_AUTH_GITHUB_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false

      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: learning-platform-redis
          property: connectionString

    plan: free
    healthCheckPath: /health/
    autoDeploy: true

    # Celery worker
  - type: worker
    name: learning-platform-celery
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A learning_platform worker --loglevel=INFO
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: learning-platform-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: learning_platform.settings

  # React Frontend - Node.js Web Service
  - type: web
    name: learning-platform-web
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve dist -s -p $PORT
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://learning-platform-api-kwp9.onrender.com
      - key: NODE_VERSION
        value: "20"
    autoDeploy: true
    plan: free
