# Generated by Django 5.2.5 on 2025-09-14 13:31

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapi', '0002_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
